---
# tasks file for wordpress
# WordPress Configuration
- name: create /var/www/{{ 192.168.0.103 }} directory for unarchiving
  file:
    path: /var/www/{{ 192.168.0.103 }}
    state: directory

- name: Download and unpack latest WordPress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/{{ 192.168.0.103 }}"
    remote_src: yes
    creates: "/var/www/{{ 192.168.0.103 }}/wordpress"

- name: Set ownership
  file:
    path: "/var/www/{{ 192.168.0.103 }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

- name: Set permissions for directories
  shell: "/usr/bin/find /var/www/{{ 192.168.0.103 }}/wordpress/ -type d -exec
    chmod 750 {} \\;"

- name: Set permissions for files
  shell: "/usr/bin/find /var/www/{{ 192.168.0.103 }}/wordpress/ -type f -exec
    chmod 640 {} \\;"

- name: Set up wp-config
  template:
    src: "wp-config.php.j2"
    dest: "/var/www/{{ 192.168.0.103 }}/wordpress/wp-config.php"
